export default {
	currentSong: {
		playback: {},
		soundObj: {},
		detail: {
			id: 12,
			title: 'Stay x Ranjha x Dr Gode',
			author: 'Bpraak • Justin Bieber • Jasleen Royal',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-6.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Stay-x-Ranjha-x-Dr-Gode-•-Bpraak-•-Justin-Bieber.mp3',
			durationMillis: 183000,
		},
		playbackStatus: {},
	},
	songs: [
		{
			id: 1,
			title: 'Voices',
			author: 'Against The Current',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Against-The-Current-Voices-OFFICIAL-VIDEO.mp3',
			durationMillis: 207000,
		},
		{
			id: 2,
			title: 'Almost Forgot About You',
			author: 'Against The Current',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-1.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Against-The-Current-Almost-Forgot-OFFICIAL-VIDEO.mp3',
			durationMillis: 209000,
		},
		{
			id: 3,
			title: 'Heart Attack - Demi Lovato',
			author: 'Against The Current & Sam Tsui',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/artworks-000131397077-p687lz-t500x500.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Heart-Attack-Demi-Lovato-Sam-Tsui-_-Chrissy-Costanza-of-ATC.mp3',
			durationMillis: 234000,
		},
		{
			id: 4,
			title: 'Gravity',
			author: 'Against The Current',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/2e6c0cd268c3f89447e33a91ac39fe44.1000x1000x1.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Against-The-Current-Gravity-Official-Music-Video.mp3',
			durationMillis: 233000,
		},
		{
			id: 5,
			title: 'Face off x Scary garry',
			author: 'Y_X Mashup',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-2.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Face-off-x-Scary-garry-Full-Version-Y_X-Mashup.mp3',
			durationMillis: 233000,
		},
		{
			id: 6,
			title: 'Alone - Fortnite Mix',
			author: 'Marshmello',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/400x400cc.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Marshmello-Alone-Fortnite-Music-Video.mp3',
			durationMillis: 203000,
		},
		{
			id: 7,
			title: 'Numb - GMV',
			author: 'Linkin Park',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/artworks-000105604285-me2956-t500x500.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Numb-Linkin-Park-GMV.mp3',
			durationMillis: 209000,
		},
		{
			id: 8,
			title: 'BIBA feat. Shirley Setia & Shah Rukh Khan',
			author: 'Marshmello x Pritam',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-3.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Marshmello-x-Pritam-BIBA-feat.-Shirley-Setia-Shah-Rukh-Khan-Official-Music-Video.mp3',
			durationMillis: 218000,
		},
		{
			id: 9,
			title: 'Genda Phool',
			author: 'Badshah',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/Genda2BPhool2BSong2BImage2BBy2BBadshah.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Badshah-–-Genda-Phool-_-Jacqueline-Fernandez-_-Payal-Dev-_-Hit-Anthem-of-the-Year-2021.mp3',
			durationMillis: 174000,
		},
		{
			id: 10,
			title: 'Gangstas Paradise',
			author: 'Coolio',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/Gangstas_paradise.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Gangstas-Paradise.mp3',
			durationMillis: 241000,
		},
		{
			id: 11,
			title: 'Marvel Anthem',
			author: 'A.R. Rahman',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-4.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Marvel-Anthem-_-A.R.-Rahman-_-Hindi.mp3',
			durationMillis: 166000,
		},
		{
			id: 12,
			title: 'Stay x Ranjha x Dr Gode',
			author: 'Bpraak • Justin Bieber • Jasleen Royal',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-6.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Stay-x-Ranjha-x-Dr-Gode-•-Bpraak-•-Justin-Bieber.mp3',
			durationMillis: 183000,
		},
		{
			id: 13,
			title: 'Enna Sona',
			author: 'A.R. Rahman - Arijit Singh',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/movieposter.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/A.R.-Rahman-Enna-Sona-Best-Video_OK-Jaanu_Arijit-Singh_Shraddha-Kapoor_Aditya-Roy.mp3',
			durationMillis: 220000,
		},
		{
			id: 14,
			title: 'Phir Kabhie',
			author: 'Arijit Singh',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/50756_1_large.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/PHIR-KABHI-Full-Video-Song-_-M.S.-DHONI-THE-UNTOLD-STORY-_Arijit-Singh_-Sushant-Singh-Disha-Patani.mp3',
			durationMillis: 215000,
		},
		{
			id: 15,
			title: 'Kabira',
			author: 'Pritam',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/raviteja-g-yeh-jawaani-hai-deewani-albumart.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Kabira-Full-Song-Yeh-Jawaani-Hai-Deewani-_-Pritam-_-Ranbir-Kapoor-Deepika-Padukone.mp3',
			durationMillis: 251000,
		},
		{
			id: 16,
			title: 'Luka Chuppi - Duniyaa',
			author: 'Akhil - Dhvani B',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/Duniya-Luka-Chuppi-Lyrics-in-Hindi.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Luka-Chuppi-Duniyaa-Full-Video-Song-_-Kartik-Aaryan-Kriti-Sanon-_-Akhil-_-Dhvani-B.mp3',
			durationMillis: 232000,
		},
		{
			id: 17,
			title: 'Lagdi Lahore di',
			author: 'Guru Randhawa - Tulsi Kumar',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/890894-streetdancer3d-review.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Full-Song-LAGDI-LAHORE-DI_Street-Dancer-3D-_-Varun-DShraddha-K-Nora-F-_Guru-RandhawaTulsi-Kumar.mp3',
			durationMillis: 203000,
		},
		{
			id: 18,
			title: 'Leja Re',
			author: 'Dhvani Bhanushali',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/MV5BMjljNTNjN2ItOWM4OS00MDE3LTg4NDgtMzIzM2QzNTEzODBmXkEyXkFqcGdeQXVyODAzNzAwOTU@._V1_.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Leja-Re-_-Dhvani-Bhanushali-_-Tanishk-Bagchi-_-Rashmi-Virag-_Radhika-Rao_-Vinay-Sapru-_-Siddharth.mp3',
			durationMillis: 259000,
		},
		{
			id: 19,
			title: 'Vaaste',
			author: 'Dhvani Bhanushali',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/pjimage-3-1588754654.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Vaaste-Song-Dhvani-Bhanushali-Tanishk-Bagchi-_-Nikhil-D-_-Bhushan-Kumar-_-Radhika-Rao-Vinay-Sapru.mp3',
			durationMillis: 266000,
		},
		{
			id: 20,
			title: 'Khairiyat',
			author: 'Arijit Singh - Pritam - Amitabh B',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/crop_480x480_1567516167_2772458.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Khairiyat-Song-_-Chhichhore-_-Arijit-Singh-_-Sushant-Shraddha-_-Pritam-Amitabh-B.mp3',
			durationMillis: 270000,
		},
		{
			id: 21,
			title: 'Raataan Lambiyan',
			author: 'Tanishk B. - Jubin Asees',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/crop_480x480_1628085090.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Raataan-Lambiyan-Full-Song-Video_Shershaah-_Sidharth–Kiara_Tanishk-B._Jubin_Asees.mp3',
			durationMillis: 229000,
		},
		{
			id: 22,
			title: 'Raataan Lambiyan',
			author: 'Tanishk B. - Jubin Asees',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/crop_480x480_1628085090.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Raataan-Lambiyan-Full-Song-Video_Shershaah-_Sidharth–Kiara_Tanishk-B._Jubin_Asees.mp3',
			durationMillis: 229000,
		},
	],
};
